version: "3.7"

services:
  nats:
    image: nats:2.10.0
    ports:
      - 4222:4222

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
