version: "3.7"

services:
  nats:
    image: nats:2.10.0
    ports:
      - 4222:4222

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

